### ISSUE TITLE
font-lock-negation-char-face not supported

### ISSUE THREAD

**Issue by peterwvj** [jd/naquadah-theme#2]
`font-lock-negation-char-face` support is currently missing. This face is quite useful for highlighting characters that are easily missed, like ! in Java. It could use any color that makes these characters stand out. The change is a one-liner, for example:

```elisp
...
'(font-lock-negation-char-face (:foreground chameleon-2))
...
```

I'm happy submit a pull request, if you prefer.

**Comment by jd** [comment]
Go for a PR! :)
